### PR TITLE
Remove deploy constraint

### PR DESCRIPTION
**Pull request by Nate-Wilkins**
Proposal for #17

### CODE REVIEW

**Comment by Syntaf** [comment]
I still need to know **why** someone would need to change their output directory, can you give me a scenario where changing the target directory is actually needed? 

The target dir really only holds temporary files. Sphinx generates output get to the target dir, then ghp-import copies that output from target dir into the gh-pages branch. I don't see any reason why someone should need to specify a different folder to an intermediate step of travis-sphinx to some other folder.

**Comment by Nate-Wilkins** [comment]
The main reason that I'd like to change the output directory is so that I can build the docs using sphinx directly alongside travis-sphinx but in all reality I could just use travis-sphinx to build and deploy. I just need the ability to customize the options going into the build process or just use sphinx.

**Comment by Syntaf** [comment]
That sounds like a needed feature then, ok.

In your PR however, you are now allowing the `--source` option to be used in `deploy`, but the source field is never used. I would revert this and allow the target dir only, then I can merge

**Comment by DavidLP** [comment]
I also would like to have this. Otherwise there is no way to use the github pages feature that expects the index.html in the docs folder. Thus I cannot use this package.

**Comment by Syntaf** [comment]
I can merge this once he made the fix I commented, though I can probably do the fix myself in a couple days.... this will be added within the week then.

**Comment by Nate-Wilkins** [comment]
I apologize, but I never got around to updating this and I think my knowledge on the subject is outdated now.

Please feel free to use the branch as you see fit (delete/update/etc).

Have a good day!

**Pull request closed without merging**
