### PR TITLE
Commands refactoring.

### PR DESCRIPTION
**Pull request by lmignon**
The primary goal of this PR is to allow to write a CNAME file into the generated documentation. In the same time, I've refactored the code to take benefit of the 'click' library and depend of the ghp-import library library in place of a clone of its repository.

### CODE REVIEW

**Comment by Syntaf** [comment]
Thanks for your work on this Imignon, i'll check out the code later tonight and see if everyone looks good to merge

**Comment by lmignon** [comment]
@Syntaf travis is red since it seems that the GH_TOKEN is missing.

**Comment by Syntaf** [comment]
Tested and LGTM, going to go ahead and merge. Are you interested in being added as maintainer considering this is such a sizable code change?

**Comment by Syntaf** [comment]
Side note, I assumed this was typo so I fixed it:

you had `travis-sphinx build --source=other/dir/doc build` in the README.md, which I changed to `travis-sphinx build --source=other/dir/doc`

**Comment by lmignon** [comment]
@syntaf Indeed it's a typo :smile: I'll be happy to be a maintainer of this lib. Thank you for ypu trust

**Pull request merged**
