### PR TITLE
Build doc with a git tag

### PR DESCRIPTION
**Pull request by reno-**
When you push a tag, it might build even if the TRAVIS_BRANCH is not set as master.
I introduce the TRAVIS_TAG variable.

### CODE REVIEW

**Comment by Syntaf** [comment]
Could you give me an example use case of this? I'm not exactly sure what you mean by when I push a tag.

Thanks for the PR!

**Comment by reno-** [comment]
I use travis-sphinx to build doc, and I use [versioneer](https://github.com/warner/python-versioneer) to take care of version's number that reflects git tags and commits.
Here is [a project](http://pixelstereo.github.io/pylekture/) that use both travis-sphinx and versioneer.

The workflow is : 
Commit on master. Everything works fine, the doc is published, the version on the doc is equivalent at 

    git describe --long --tags

But when I decided that the last commit is ok to become the last release, I do a 'git tag', and I expected that the doc reflects the version of the package.
e. g. :
* Now package is 0.2.0+18.g2abe2dd (18 commits since the tag 0.2.0)
* If I tag this commit 0.2.1, I would expect that the documentation will be 0.2.1.

This is because I create tag only when I'm sure that the last commit is ok. 
 
Maybe I'm the only one working like this, but maybe not !!

cheers,

renaud

**Comment by Syntaf** [comment]
ok I looked up the variable in the travis docs so correct me if I'm wrong: but `TRAVIS_TAG` will contain a string of what tag was pushed if the current build was the result of a tag. So what you're doing here is saying this normal PR would introduce the logic:

do our normal checks, **but** if it's a tag, build it regardless of what branch it is on. Correct?

Sounds good to me

Thanks for trying to explain this, I've never worked with git tags and I'm unsure how they interact with Travis-CI.

**Comment by reno-** [comment]
Yes, I simplify the change with another commit.

If normal_check OR tag => build

**Comment by Syntaf** [comment]
Awesome, Thank you reno!

**Pull request merged**
